//"use client";
import 'bootstrap/dist/css/bootstrap.min.css';
import Styles from './globals.css';
import Link from 'next/link'
import { Controls } from './Controls';
//import { useState} from 'react';

 export const metadata = {
   title: "Web Tutorials",
   description: "Generated by Green",
 };

export default async function RootLayout(props) {
  console.log('공통 레이아웃 작동');
  /*
  const [topics, setTopics] = useState([]);

  useEffect(()=>{
    fetch('http://localhost:9999/topics/')
    .then(r=>r.json())
    .then(result=>{
      setTopics(result);
      
    });
  },[]);
  */
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}topics`,{ cache: 'no-store' });
  const topics = await res.json(); //json->object

  console.log(topics);
  return (
    <html lang="en">
      <body>
        <nav className='navbar bg-light'>
          <div className="container">
            <Link href="/" className="navbar-brand">WEB</Link>
            <ul className="nav">
              {
                topics.map(topic=>
                  <li key={topic.id} className="nav-item">
                    <Link href={`/read/${topic.id}`} className="nav-link">{topic.title}</Link>
                  </li>
                )              
              }
                    
            </ul>
          </div>
        </nav>
        <main className="container my-3">
          {props.children}
          <hr/>
          <Controls/>
        </main>
      </body>
    </html>
  );
}
